name: oil_connect
description: "A platform  for user to request and manage oil transport services efficiently."

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General dependencies
  web: ^1.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_country_code_picker: ^0.1.9+1
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.0
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.1.4
  flutter_dotenv: ^5.0.2
  jwt_decoder: ^2.0.1
  flutter_screenutil: ^5.5.4
  google_maps_flutter: ^2.12.3
  permission_handler: ^11.3.1
  open_file: ^3.5.10
  dropdown_search: ^5.0.3
  geolocator: ^13.0.0
  geocoding: ^2.1.0
  icons_plus: ^5.0.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.3
  mime: ^2.0.0
  http_parser: ^4.1.2
  connectivity_plus: ^5.0.2
  intl: ^0.20.2
  socket_io_client: ^2.0.3+1
  flutter_polyline_points: ^2.1.0
  pin_code_fields: ^8.0.1
  path_provider: ^2.1.5
  share_plus: 
  font_awesome_flutter: ^10.12.0
  dropdown_button2: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
